manifest:
  self:
    path: uhk
  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: sdk-nrf
      remote: sdk
      path: nrf
      revision: v2.5.2
      import:
        path-prefix: nrfconnect
      clone-depth: 1
    - name: hal_nxp
      remote: zephyr
      path: zephyr-hal-nxp
      clone-depth: 1
